# Generated by Django 2.1.7 on 2019-03-31 16:38

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('text', models.CharField(max_length=45, null=True)),
                ('createdDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('createdDate', models.DateTimeField(auto_now=True)),
                ('updateDate', models.DateTimeField(auto_now_add=True)),
                ('publishDate', models.DateTimeField(auto_now_add=True)),
                ('allowComment', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/%Y-%m-%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Blog.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstName', models.CharField(max_length=150, null=True)),
                ('lastName', models.CharField(max_length=150, null=True)),
                ('nationalCode', models.CharField(max_length=10, null=True)),
                ('tellNumber', models.CharField(max_length=17, null=True)),
                ('birthDate', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('createdDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
