# Generated by Django 2.1.7 on 2019-03-31 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiMedia', models.FileField(blank=True, null=True, upload_to='')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blog.Post')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.CharField(max_length=200)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Blog.Post')),
            ],
        ),
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Post')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Tag')),
            ],
        ),
    ]
