# Generated by Django 2.1.7 on 2019-03-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_multimedia_news_posttags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttags',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posttags',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='Blog.Tag'),
        ),
        migrations.DeleteModel(
            name='PostTags',
        ),
    ]
